<?php
return [
    "planLimitations" => [
        "1" => [35000, 3],
        "2" => [500, 1],
        "3" => [1000, 1],
        "4" => [2000, 1],
        "5" => [3000, 1],
        "6" => [5000, 1],
        "7" => [10000, 2],
        "8" => [20000, 2],
        "9" => [25000, 2],
        "10" => [30000, 2],
        "11" => [35000, 3],
        "12" => [40000, 3],
        "13" => [45000, 3],
        "14" => [50000, 3],
        "15" => [100000, 5],
        "16" => [200000, 5],
        "17" => [300000, 5],
        "18" => [400000, 5],
        "19" => [500000, 10],
        "20" => [600000, 10],
        "21" => [700000, 10],
        "22" => [800000, 10],
        "23" => ["Unlimited", "Unlimited"],
        "24" => [35000, 3],
        "25" => [500, 1],
        "26" => [1000, 1],
        "27" => [2000, 1],
        "28" => [3000, 1],
        "29" => [5000, 1],
        "30" => [10000, 2],
        "31" => [20000, 2],
        "32" => [25000, 2],
        "33" => [30000, 2],
        "34" => [35000, 3],
        "35" => [40000, 3],
        "36" => [45000, 3],
        "37" => [50000, 3],
        "38" => [100000, 5],
        "39" => [200000, 5],
        "40" => [300000, 5],
        "41" => [400000, 5],
        "42" => [500000, 10],
        "43" => [600000, 10],
        "44" => [700000, 10],
        "45" => [800000, 10],
        "46" => ["Unlimited", "Unlimited"],
        "47" => [100000, 5],
        "48" => [100000, 5],
        "49" => [100000, 5],
        "50" => [100000, 5],
        "51" => [100000, 5],
        "52" => [200000, 5],
        "53" => [200000, 5],
        "54" => [200000, 5],
        "55" => [200000, 5],
        "56" => [200000, 5],
        "57" => [300000, 5],
        "58" => [300000, 5],
        "59" => [300000, 5],
        "60" => [300000, 5],
        "61" => [300000, 5],
        "62" => [400000, 5],
        "63" => [400000, 5],
        "64" => [400000, 5],
        "65" => [400000, 5],
        "66" => [400000, 5],
        "67" => [500000, 10],
        "68" => [500000, 10],
        "69" => [500000, 10],
        "70" => [500000, 10],
        "71" => [500000, 10],
        "72" => [600000, 10],
        "73" => [600000, 10],
        "74" => [600000, 10],
        "75" => [600000, 10],
        "76" => [600000, 10],
        "77" => [700000, 10],
        "78" => [700000, 10],
        "79" => [700000, 10],
        "80" => [700000, 10],
        "81" => [700000, 10],
        "82" => [800000, 10],
        "83" => [800000, 10],
        "84" => [800000, 10],
        "85" => [800000, 10],
        "86" => [800000, 10],
        "87" => ["Unlimited", "Unlimited"],
        "88" => ["Unlimited", "Unlimited"],
        "89" => ["Unlimited", "Unlimited"],
        "90" => ["Unlimited", "Unlimited"],
        "91" => ["Unlimited", "Unlimited"],
        "92" => ["Unlimited", "Unlimited"],
    ],
    "planFeatureLimitations" => [
        "1" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => false,
            "promotion"         => true,
            "localInventory"    => false,
        ],
        "2" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => false,
            "includeExclude"    => false,
            "importExport"      => false,
            "promotion"         => false,
            "localInventory"    => false,
        ],
        "3" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => false,
            "includeExclude"    => false,
            "importExport"      => false,
            "promotion"         => false,
            "localInventory"    => false,
        ],
        "4" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => false,
            "includeExclude"    => false,
            "importExport"      => false,
            "promotion"         => false,
            "localInventory"    => false,
        ],
        "5" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => false,
            "includeExclude"    => false,
            "importExport"      => false,
            "promotion"         => false,
            "localInventory"    => false,
        ],
        "6" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => false,
            "includeExclude"    => false,
            "importExport"      => false,
            "promotion"         => false,
            "localInventory"    => false,
        ],
        "7" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => false,
            "includeExclude"    => true,
            "importExport"      => false,
            "promotion"         => true,
            "localInventory"    => false,
        ],
        "8" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => false,
            "includeExclude"    => true,
            "importExport"      => false,
            "promotion"         => true,
            "localInventory"    => false,
        ],
        "9" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => false,
            "includeExclude"    => true,
            "importExport"      => false,
            "promotion"         => true,
            "localInventory"    => false,
        ],
        "10" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => false,
            "includeExclude"    => true,
            "importExport"      => false,
            "promotion"         => true,
            "localInventory"    => false,
        ],
        "11" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => false,
            "promotion"         => true,
            "localInventory"    => false,
        ],
        "12" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => false,
            "promotion"         => true,
            "localInventory"    => false,
        ],
        "13" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => false,
            "promotion"         => true,
            "localInventory"    => false,
        ],
        "14" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => false,
            "promotion"         => true,
            "localInventory"    => false,
        ],
        "15" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "16" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "17" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "18" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "19" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "20" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "21" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "22" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "23" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "24" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => false,
            "promotion"         => true,
            "localInventory"    => false,
        ],
        "25" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => false,
            "includeExclude"    => false,
            "importExport"      => false,
            "promotion"         => false,
            "localInventory"    => false,
        ],
        "26" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => false,
            "includeExclude"    => false,
            "importExport"      => false,
            "promotion"         => false,
            "localInventory"    => false,
        ],
        "27" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => false,
            "includeExclude"    => false,
            "importExport"      => false,
            "promotion"         => false,
            "localInventory"    => false,
        ],
        "28" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => false,
            "includeExclude"    => false,
            "importExport"      => false,
            "promotion"         => false,
            "localInventory"    => false,
        ],
        "29" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => false,
            "includeExclude"    => false,
            "importExport"      => false,
            "promotion"         => false,
            "localInventory"    => false,
        ],
        "30" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => false,
            "includeExclude"    => true,
            "importExport"      => false,
            "promotion"         => true,
            "localInventory"    => false,
        ],
        "31" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => false,
            "includeExclude"    => true,
            "importExport"      => false,
            "promotion"         => true,
            "localInventory"    => false,
        ],
        "32" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => false,
            "includeExclude"    => true,
            "importExport"      => false,
            "promotion"         => true,
            "localInventory"    => false,
        ],
        "33" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => false,
            "includeExclude"    => true,
            "importExport"      => false,
            "promotion"         => true,
            "localInventory"    => false,
        ],
        "34" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => false,
            "promotion"         => true,
            "localInventory"    => false,
        ],
        "35" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => false,
            "promotion"         => true,
            "localInventory"    => false,
        ],
        "36" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => false,
            "promotion"         => true,
            "localInventory"    => false,
        ],
        "37" => [
            "bulkEdit"          => true,
            "customImage"       => false,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => false,
            "promotion"         => true,
            "localInventory"    => false,
        ],
        "38" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "39" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "40" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "41" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "42" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "43" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "44" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "45" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "46" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "47" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "48" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "49" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "50" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "51" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "52" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "53" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "54" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "55" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "56" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "57" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "58" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "59" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "60" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "61" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "62" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "63" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "64" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "65" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "66" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "67" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "68" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "69" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "70" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "71" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "72" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "73" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "74" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "75" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "76" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "77" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "78" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "79" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "80" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "81" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "82" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "83" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "84" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "85" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "86" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "87" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "88" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "89" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "90" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "91" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
        "92" => [
            "bulkEdit"          => true,
            "customImage"       => true,
            "metafieldsMapping" => true,
            "includeExclude"    => true,
            "importExport"      => true,
            "promotion"         => true,
            "localInventory"    => true,
        ],
    ]
];
