<?php

return [
    'headerFieldsName' => [
        'Feed Id', 'Product Id', 'Variant Id', 'Title', 'Description', 'Score', 'Product Type', 'Brand', 'Condition', 'Age Group',
        'Gender', 'Product Category', 'GTIN', 'Sku', 'Ads Grouping', 'Ads Labels', 'Adult-Orianted Products', 'Color', 'Cost Of Goods Sold',
        'Custom Label 0', 'Custom Label 1', 'Custom Label 2', 'Custom Label 3', 'Custom Label 4', 'Material', 'Pattern',
        'Identifier Exists', 'Promotion Id', 'Shipping Label', 'Size', 'Size System', 'Size Type', 'Tax Category',
        'Unit Pricing Measure', 'Unit Pricing Base Measure', 'Energy Efficiency Class', 'Expiration Date', 'Installment',
        'Is Bundle', 'Loyalty Points', 'Max Energy Efficiency Class', 'Max Handling Time', 'Min Energy Efficiency Class',
        'Min Handling Time', 'Multipack', 'Shipping', 'Shipping Height', 'Shipping Length', 'Shipping Weight', 'Shipping Width',
        'Product Height', 'Product Length', 'Product Weight', 'Product Width', 'Transit Time Label', 'Pause',
        'Sale Price Effective Date', 'Subscription Cost', 'Product Highlights (1,2,3,4,5,6)', 'Featured Image', 'Additional Image Links 0', 'Additional Image Links 1',
        'Additional Image Links 2', 'Additional Image Links 3', 'Additional Image Links 4', 'Additional Image Links 5',
        'Additional Image Links 6', 'Additional Image Links 7', 'Additional Image Links 8', 'Additional Image Links 9',
    ],
    'headerFieldsToReadCsv' => [
        /* 'Feed Id', 'Product Id', 'Variant Id', */'App Id', 'Title', 'Description', 'Score', 'Product Type', 'Brand', 'Condition', 'Age Group',
        'Gender', 'Product Category', 'GTIN', 'Sku', 'Ads Grouping', 'Ads Labels', 'Adult-Orianted Products', 'Color', 'Cost Of Goods Sold',
        'Custom Label 0', 'Custom Label 1', 'Custom Label 2', 'Custom Label 3', 'Custom Label 4', 'Material', 'Pattern',
        'Identifier Exists', 'Promotion Id', 'Shipping Label', 'Size', 'Size System', 'Size Type', 'Tax Category',
        'Unit Pricing Measure', 'Unit Pricing Base Measure', 'Energy Efficiency Class', 'Expiration Date', 'Installment',
        'Is Bundle', 'Loyalty Points', 'Max Energy Efficiency Class', 'Max Handling Time', 'Min Energy Efficiency Class',
        'Min Handling Time', 'Multipack', 'Shipping', 'Shipping Height', 'Shipping Length', 'Shipping Weight', 'Shipping Width',
        'Product Height', 'Product Length', 'Product Weight', 'Product Width', 'Transit Time Label', 'Pause',
        'Sale Price Effective Date', 'Subscription Cost', 'Product Highlight 1', 'Product Highlight 2', 'Product Highlight 3',
        'Product Highlight 4', 'Product Highlight 5', 'Product Highlight 6', 'Featured Image', 'Additional Image Links 0', 'Additional Image Links 1',
        'Additional Image Links 2', 'Additional Image Links 3', 'Additional Image Links 4', 'Additional Image Links 5',
        'Additional Image Links 6', 'Additional Image Links 7', 'Additional Image Links 8', 'Additional Image Links 9',
    ],
    'matchColumName' => [
        'gTIN' => 'barcode',
        'featured Image' => 'image',
        'product Type' => 'productTypes',
        'condition' => 'productCondition',
        'adult-Orianted Products' => 'adult',
        'promotion Id' => 'promotionIds',
        'size' => 'sizes',
        'product Category' => 'product_category_id',
        'additional Image Links 0' => 'additionalImage01',
        'additional Image Links 1' => 'additionalImage02',
        'additional Image Links 2' => 'additionalImage03',
        'additional Image Links 3' => 'additionalImage04',
        'additional Image Links 4' => 'additionalImage05',
        'additional Image Links 5' => 'additionalImage06',
        'additional Image Links 6' => 'additionalImage07',
        'additional Image Links 7' => 'additionalImage08',
        'additional Image Links 8' => 'additionalImage09',
        'additional Image Links 9' => 'additionalImage10',
        'product Highlights (1,2,3,4,5,6)' => 'productHighlights',
        'loyalty Points' => 'loyaltyPoints',
        'ads Label' => 'adsLabels',
    ],
    'valuesToDecodeForFeedData' => [
        'costOfGoodsSold', 'promotionIds', 'unitPricingMeasure', 'unitPricingBaseMeasure', 'installment', 'loyaltyPoints', 'subscriptionCost', 'shippingHeight', 'shippingWidth', 'shippingLength', 'shippingWeight', 'productHeight', 'productLength', 'productWidth', 'productWeight',
    ],
    'editedProductsColums' => [
        'color', 'sizes', 'material', 'pattern', 'sizeSystem', 'sizeType', 'unitPricingMeasure', 'unitPricingBaseMeasure', 'multipack', 'isBundle', 'promotionIds', 'salePriceEffectiveDate', 'adult', 'costOfGoodsSold', 'installment', 'loyaltyPoints', 'installment', 'energyEfficiencyClass', 'minEnergyEfficiencyClass', 'maxEnergyEfficiencyClass', 'maxHandlingTime', 'minHandlingTime',
        'shipping', 'shippingHeight', 'shippingWidth', 'shippingLength', 'shippingWeight', 'productHeight', 'productLength', 'productWidth', 'productWeight', 'transitTimeLabel', 'pause', 'subscriptionCost', 'identifierExists', 'expirationDate',
    ],
    'productImagesColums' => [
        'additionalImage01', 'additionalImage02', 'additionalImage03', 'additionalImage04', 'additionalImage05', 'additionalImage06', 'additionalImage07', 'additionalImage08', 'additionalImage09', 'additionalImage10',
    ],
    'productHighlights' => [
        'productHighlight1', 'productHighlight2', 'productHighlight3', 'productHighlight4', 'productHighlight5', 'productHighlight6',
    ],
    'productLabels' => [
        'customLabel0', 'customLabel1', 'customLabel2', 'customLabel3', 'customLabel4', 'adsLabels', 'adsGrouping', 'shippingLabel', 'taxCategory',
    ],
    'mapKeys' => [
        'feed Id' => 'feed_setting_id',
        'gTIN' => 'barcode',
        'featured Image' => 'image',
        'product Type' => 'productTypes',
        'condition' => 'productCondition',
        'adult-Orianted Products' => 'adult',
        'promotion Id' => 'promotionIds',
        'size' => 'sizes',
        'product Category' => 'product_category_id',
        'additional Image Links 0' => 'additionalImage01',
        'additional Image Links 1' => 'additionalImage02',
        'additional Image Links 2' => 'additionalImage03',
        'additional Image Links 3' => 'additionalImage04',
        'additional Image Links 4' => 'additionalImage05',
        'additional Image Links 5' => 'additionalImage06',
        'additional Image Links 6' => 'additionalImage07',
        'additional Image Links 7' => 'additionalImage08',
        'additional Image Links 8' => 'additionalImage09',
        'additional Image Links 9' => 'additionalImage10',
        'product Highlight 1' => 'productHighlight1',
        'product Highlight 2' => 'productHighlight2',
        'product Highlight 3' => 'productHighlight3',
        'product Highlight 4' => 'productHighlight4',
        'product Highlight 5' => 'productHighlight5',
        'product Highlight 6' => 'productHighlight6',
        'loyalty Points' => 'loyaltyPoints',
        'ads Label' => 'adsLabels',
    ],

];
