<?php
return [
    'syncForm' => [
        'name'                  =>  ['required', 'string'],
        'market'                =>  ['required', 'string'],
        'country'               =>  ['required', 'string'],
        'language'              =>  ['required', 'string'],
        'currency'              =>  ['required', 'string'],
        "channel"               =>  ["required", "string", "in:online,local"],
        "shipping"              =>  ["required", "string", "in:auto,manual"],
        "productIdFormat"       =>  ["required", "string", "in:global,sku,variant"],
        "whichProducts"         =>  ["required", "string", "in:all,collection"],
        "includedCollections"   =>  ["required_if:whichProducts,collection", "array"],
        'excludedCollections'   =>  ["nullable", "array"],
        'productTitle'          =>  ['required', "string", 'in:default,seo'],
        "productDescription"    =>  ['required', "string", 'in:default,seo'],
        "variantSubmission"     =>  ["required", "string", "in:first,all"],
        "brandSubmission"       =>  ["required", "string", "in:vendor,domain"],
        'productIdentifiers'    =>  ["required", "string", "in:true,false"],
        'barcode'               =>  ["nullable", "boolean"],
        "salePrice"             =>  ["nullable", "boolean"],
        "secondImage"           =>  ["nullable", "boolean"],
        "additionalImages"      =>  ["nullable", "boolean"],
        "product_category_id"   =>  ["nullable", "exists:product_categories,id", "integer"],
        "ageGroup"              =>  ["required", "in:newborn,infant,toddler,kids,adult", 'string'],
        "gender"                =>  ["required", "in:male,female,unisex", 'string'],
        "productCondition"      =>  ["required", "in:new,refurbished,used", 'string'],
        "utm_campaign"          =>  ["nullable", 'string'],
        "utm_source"            =>  ["nullable", 'string'],
        "utm_medium"            =>  ["nullable", 'string'],
    ],
    'localFeedForm' => [
        'feed_name'                =>  ['required', 'string'],
        'feed_setting_id'          =>  ["required", "exists:feed_settings,id"],
        'feed_type'                =>  ['required', 'string'],
        'code'                     =>  ['required', 'string'],
        'availability'             =>  ['nullable', 'string'],
        'salePriceEffectiveDate'   =>  ['nullable', 'array'],
        'salePrice'                =>  ['nullable', 'boolean'],
        'pickupMethod'             =>  ['nullable', 'string'],
        'pickupSla'                =>  ['nullable', 'string'],
        'instoreProductLocation'   =>  ['nullable', 'string'],
    ],
    'updateFeedForm' => [
        'id'                    =>  ["required", "exists:feed_settings,id"],
        'merchantAccountId'     =>  ['required', 'string'],
        'merchantAccountName'   =>  ['required', 'string'],
        'name'                  =>  ['required', 'string'],
        'market'                =>  ['required', 'string'],
        'country'               =>  ['required', 'string'],
        'language'              =>  ['required', 'string'],
        'currency'              =>  ['required', 'string'],
        "shipping"              =>  ["required", "string", "in:auto,manual"],
        "productIdFormat"       =>  ["required", "string", "in:global,sku,variant"],
        "whichProducts"         =>  ["required", "string", "in:all,collection"],
        "includedCollections"   =>  ["nullable", "array"],
        'excludedCollections'   =>  ["nullable", "array"],
        'productTitle'          =>  ['required', "string", 'in:default,seo'],
        "productDescription"    =>  ['required', "string", 'in:default,seo'],
        "variantSubmission"     =>  ["required", "string", "in:first,all"],
        "brandSubmission"       =>  ["required", "string", "in:vendor,domain"],
        'productIdentifiers'    =>  ["nullable", "boolean"],
        'barcode'               =>  ["nullable", "boolean"],
        "salePrice"             =>  ["nullable", "boolean"],
        "secondImage"           =>  ["nullable", "boolean"],
        "additionalImages"      =>  ["nullable", "boolean"],
        "product_category_id"   =>  ["nullable", "exists:product_categories,id", "integer"],
        "ageGroup"              =>  ["required", "in:newborn,infant,toddler,kids,adult", 'string'],
        "gender"                =>  ["required", "in:male,female,unisex", 'string'],
        "productCondition"      =>  ["required", "in:new,refurbished,used", 'string'],
        "utm_campaign"          =>  ["nullable", 'string'],
        "utm_source"            =>  ["nullable", 'string'],
        "utm_medium"            =>  ["nullable", 'string'],
    ],
    'SyncNowForm' => [
        "variantId"             =>  ["required", "regex:/^[0-9]{1,20}\d:[0-9]{1,20}\d$/"]
    ],
    // 'PupdateForm' => [
    //     'title'                =>  ['nullable', "string", "max:150"],
    //     'description'          =>  ['nullable', 'string', "max:4990"],
    //     'product_category_id'  =>  ['nullable', 'exists:product_categories,id', 'integer'],
    //     "ageGroup"             =>  ['nullable', "in:newborn,infant,toddler,kids,adult", 'string'],
    //     "gender"               =>  ['nullable', "in:male,female,unisex", 'string'],
    //     "productCondition"     =>  ['nullable', "in:new,refurbished,used", 'string'],
    //     // "customLabel"       =>  [ "nullable", "array", "max:5"],
    //     "customLabel0"         =>  ["nullable", "string", "max:191"],
    //     "customLabel1"         =>  ["nullable", "string", "max:191"],
    //     "customLabel2"         =>  ["nullable", "string", "max:191"],
    //     "customLabel3"         =>  ["nullable", "string", "max:191"],
    //     "customLabel4"         =>  ["nullable", "string", "max:191"],
    //     "color"                =>  ['nullable', "string", "max:150"],
    //     "adult"                =>  ['nullable', "boolean"],
    //     "changeMaterial"       =>  ['nullable', "string"],
    //     "changeSize"           =>  ['nullable', "string", "max:150"],
    //     "costOfGoodsSold"      =>  ['nullable', "string", "max:150"],
    //     "multipack"            =>  ['nullable', "string", "max:150"],
    //     "pattern"              =>  ['nullable', "string", "max:150"],
    //     "productTypes"         =>  ['nullable', "string"],
    //     "sizeSystem"           =>  ['nullable', "string"],
    //     "sizes"                =>  ['nullable', "string"],
    //     "sizeType"             =>  ['nullable', "string"],
    //     "vendor"               =>  ['nullable', "string"],
    //     "unitPricingBaseMeasure"  =>  ['nullable', "string"],
    //     "unitPricingMeasure"      =>   ['nullable', "string"],
    //     "unitValue"               =>   ['nullable', "string"],
    //     "baseValue"               =>   ["nullable", "string"],
    //     "ProductDetailsSectionName.*"  => ["nullable", "string"],
    //     "*.SectionIndexAttributeName.*" => ["nullable", "string"],
    //     ".*SectionIndexAttributeValue.*" => ["nullable", "string"],
    //     "adsGrouping" => ["nullable", "string"],
    //     "adsLabels"   => ["nullable", "string"],
    //     "highlight0"  => ["nullable", "string"],
    //     "highlight1"  => ["nullable", "string"],
    //     "highlight2"  => ["nullable", "string"],
    //     "highlight3"  => ["nullable", "string"],
    //     "highlight4"  => ["nullable", "string"],
    //     "highlight5"  => ["nullable", "string"],
    //     "isBundle"    => ["nullable", "string"],
    //     "material"    => ["nullable", "string"],
    //     "identifierExists" => ["nullable", "string"],
    //     "shippingLabel" => ["nullable", "string"],
    //     "taxCategory"   => ["nullable", "string"],
    //     "promotionIds" => ["nullable", "array"],
    //     "productHighlights" => ['nullable', 'array'],
    //     "productDetails" => ['nullable', 'array']
    // ],
    'PdeleteForm' => [
        'id'             =>  ["required", "exists:shop_products,productId"]
    ],
    'singleProductDeleteForm' => [
        'id'             =>  ["required", "exists:shop_product_variants,id"]
    ],
    'bulkProductDeleteForm' => [
        'ids'             =>  ["required"],
        'feedid'          =>  ["required", "exists:feed_settings,id"],
        'tabValue'        =>  ['nullable', 'string'],
    ],
    'singleExcludedProductDeleteForm' => [
        'id'             =>  ["required", "exists:excluded_products,id"]
    ],
    'bulkExcludedProductDeleteForm' => [
        'ids'             =>  ["required"],
        'feedid'          =>  ["required", "exists:feed_settings,id"],
        'tabValue'        =>  ['nullable', 'string'],
    ],
    'includeProductsForm' => [
        'ids'             =>  ["required"],
        'feedid'          =>  ["required", "exists:feed_settings,id"]
    ],
    'syncStatusForm' => [
        'feedId'          =>  ["required", "exists:feed_settings,id"]
    ],
    'getMetafieldsform' => [
        'resourceType'    =>  ["required", "string", "in:variant,product"],
    ],
    'FeedDeleteForm' => [
        'id'             =>  ["required", "exists:feed_settings,id"]
    ],
    'syncDataFromShopify' => [
        'ids'                           =>  ["required"],
        'feedId'                        =>  ["required", "exists:feed_settings,id"],
        'resourceType'                  =>  ['nullable', 'string'],
        'tabValue'                      =>  ['nullable', 'string'],
        'inputData.description'         =>  ['nullable', 'exclude_if:inputData.description,false', 'boolean'],
        'inputData.pAdditionalImages'   =>  ['nullable', 'exclude_if:inputData.pAdditionalImages,false', 'boolean'],
        'inputData.seoDescription'      =>  ['nullable', 'exclude_if:inputData.seoDescription,false', 'boolean'],
        'inputData.seoTitle'            =>  ['nullable', 'exclude_if:inputData.seoTitle,false', 'boolean'],
        'inputData.title'               =>  ['nullable', 'exclude_if:inputData.title,false', 'boolean'],
        'inputData.productImages'       =>  ['nullable', 'exclude_if:inputData.productImages,false', 'boolean'],
        'inputData.productPrice'        =>  ['nullable', 'exclude_if:inputData.productPrice,false', 'boolean'],
        'inputData.variantImage'        =>  ['nullable', 'exclude_if:inputData.variantImage,false', 'boolean'],
        'inputData.metafields'          =>  ['nullable', 'array'],
        'inputData.metafieldResource'   =>  ['nullable', 'string', 'in:variant,product,none'],
    ],
    "bulkEditForm" => [
        'ids'                                   =>  ["required"],
        'feedId'                                =>  ["required", "exists:feed_settings,id"],
        'tabValue'                              =>  ['nullable', 'string'],
        'bulkFields.adsGrouping'                =>  ["nullable", "string"],
        'bulkFields.adsLabels'                  =>  ["nullable", "string"],
        'bulkFields.adult'                      =>  ["nullable", "string"],
        'bulkFields.ageGroup'                   =>  ["nullable", "in:newborn,infant,toddler,kids,adult", 'string'],
        'bulkFields.condition'                  =>  ["nullable", "in:new,refurbished,used", 'string'],
        'bulkFields.color'                      =>  ["nullable", "string"],
        'bulkFields.costOfGoodsSold'            =>  ["nullable", "array"],
        'bulkFields.customLabel0'               =>  ["nullable", "string"],
        'bulkFields.customLabel1'               =>  ["nullable", "string"],
        'bulkFields.customLabel2'               =>  ["nullable", "string"],
        'bulkFields.customLabel3'               =>  ["nullable", "string"],
        'bulkFields.customLabel4'               =>  ["nullable", "string"],
        'bulkFields.gender'                     =>  ["nullable", "in:male,female,unisex", 'string'],
        'bulkFields.product_category_id'        =>  ["nullable", "exists:product_categories,id", "integer"],
        'bulkFields.material'                   =>  ["nullable", "string"],
        'bulkFields.pattern'                    =>  ["nullable", "string"],
        'bulkFields.identifierExists'           =>  ["nullable", "string"],
        'bulkFields.productTypes'               =>  ["nullable", "string"],
        'bulkFields.promotionIds'               =>  ["nullable", "array"],
        'bulkFields.return_policy_label'        =>  ["nullable", "string"],
        'bulkFields.shippingLabel'              =>  ["nullable", "string"],
        'bulkFields.sizes'                      =>  ["nullable", "string"],
        'bulkFields.sizeSystem'                 =>  ["nullable", "in:AU,BR,CN,DE,EU,FR,IT,JP,MEX,UK,US", "string"],
        'bulkFields.sizeType'                   =>  ["nullable", "in:regular,petite,plus,tall,big,maternity", "string"],
        'bulkFields.taxCategory'                =>  ["nullable", "string"],
        'bulkFields.unitPricingMeasure'         =>  ["nullable", "array"],
        'bulkFields.unitPricingBaseMeasure'     =>  ["nullable", "array"],
        'bulkFields.brand'                      =>  ["nullable", "string"],
        'bulkFields.availabilityDate'           =>  ["nullable", "string"],
        'bulkFields.availability'               =>  ["nullable", "in:in_stock,out_of_stock,preorder,backorder", "string"],
        'bulkFields.energyEfficiencyClass'      =>  ["nullable", "in:A+++,A++,A+,A,B,C,D,E,F,G", "string"],
        'bulkFields.expirationDate'             =>  ["nullable", "string"],
        'bulkFields.installment'                =>  ["nullable", "array"],
        'bulkFields.isBundle'                   =>  ["nullable", "string"],
        'bulkFields.loyaltyPoints'              =>  ["nullable", "array"],
        'bulkFields.maxEnergyEfficiencyClass'   =>  ["nullable", "in:A+++,A++,A+,A,B,C,D,E,F,G", "string"],
        'bulkFields.maxHandlingTime'            =>  ["nullable", "string"],
        'bulkFields.minEnergyEfficiencyClass'   =>  ["nullable", "in:A+++,A++,A+,A,B,C,D,E,F,G", "string"],
        'bulkFields.minHandlingTime'            =>  ["nullable", "string"],
        'bulkFields.multipack'                  =>  ["nullable", "string"],
        'bulkFields.shippingHeight'             =>  ["nullable", "array"],
        'bulkFields.shippingLength'             =>  ["nullable", "array"],
        'bulkFields.shippingWeight'             =>  ["nullable", "array"],
        'bulkFields.shippingWidth'              =>  ["nullable", "array"],
        'bulkFields.productHeight'              =>  ["nullable", "array"],
        'bulkFields.productLength'              =>  ["nullable", "array"],
        'bulkFields.productWeight'              =>  ["nullable", "array"],
        'bulkFields.productWidth'               =>  ["nullable", "array"],
        'bulkFields.transitTimeLabel'           =>  ["nullable", "string"],
        'bulkFields.pause'                      =>  ["nullable", "in:ads,all", "string"],
        'bulkFields.salePriceEffectiveDate'     =>  ["nullable", "array"],
        'bulkFields.subscriptionCost'           =>  ["nullable", "array"],
        'bulkFields.shipping'                   =>  ["nullable", "array"],
    ],
    "ticketValidationForm" => [
        "email"             => ['required', 'email'],
        "subject"           => ['required', 'string'],
        "description"       => ['required', 'string'],
        "attachments.*"     => ['nullable', 'image', 'mimes:jpeg,png,jpg,gif,svg,webp']
    ],
    "suggestionValidationForm" => [
        "email"             => ['required', 'email'],
        "subject"           => ['required', 'string'],
        "description"       => ['required', 'string'],
        "attachments.*"     => ['nullable', 'image', 'mimes:jpeg,png,jpg,gif,svg,webp']
    ],
    "ReviewForm" => [
        'rating'              => 'required|integer|between:1,5',
        "clicked_on"          => "required|in:good,bad|string",
        "review_text"         => "required|string|min:100|max:500",
    ],
    "exportProductsForm" => [
        'selectedProducts'                      =>  ["required", "exists:shop_product_variants,id"],
        'feedId'                                =>  ["required", "exists:feed_settings,id"],
    ],
    'PupdateForm' => [
        'title'                          =>  ['nullable', "string", "max:150"],
        'description'                    =>  ['nullable', 'string', "max:4990"],
        'product_category_id'            =>  ['nullable', 'exists:product_categories,id', 'integer'],
        "ageGroup"                       =>  ['nullable', "in:newborn,infant,toddler,kids,adult", 'string'],
        "gender"                         =>  ['nullable', "in:male,female,unisex", 'string'],
        "productCondition"               =>  ['nullable', "in:new,refurbished,used", 'string'],
        "customLabel0"                   =>  ["nullable", "string", "max:191"],
        "customLabel1"                   =>  ["nullable", "string", "max:191"],
        "customLabel2"                   =>  ["nullable", "string", "max:191"],
        "customLabel3"                   =>  ["nullable", "string", "max:191"],
        "customLabel4"                   =>  ["nullable", "string", "max:191"],
        "color"                          =>  ['nullable', "string", "max:150"],
        "adult"                          =>  ['nullable', "boolean"],
        "identifierExists"               =>  ['nullable', "string"],
        "material"                       =>  ['nullable', "string"],
        "sizes"                          =>  ['nullable', "string", "max:150"],
        "costOfGoodsSold"                =>  ['nullable', "string", "max:150"],
        "multipack"                      =>  ['nullable', "string", "max:150"],
        "pattern"                        =>  ['nullable', "string", "max:150"],
        "productTypes"                   =>  ['nullable', "string"],
        "sizeSystem"                     =>  ['nullable', "string"],
        "size"                           =>  ['nullable', "string"],
        "sizeType"                       =>  ['nullable', "string"],
        "brand"                          =>  ['nullable', "string"],
        "unitPricingBaseMeasure"         =>  ['nullable', "array"],
        "unitPricingMeasure"             =>  ['nullable', "array"],
        "adsGrouping"                    =>  ["nullable", "string"],
        "adsLabels"                      =>  ["nullable", "string"],
        "isBundle"                       =>  ["nullable", "string"],
        "material"                       =>  ["nullable", "string"],
        "shippingLabel"                  =>  ["nullable", "string"],
        "taxCategory"                    =>  ["nullable", "string"],
        "promotionIds"                   =>  ["nullable", "array"],
        "productHighlights"              =>  ['nullable', 'array'],
        "productDetails"                 =>  ['nullable', 'array'],
        "availability"                   =>  ['nullable', 'string'],
        "availabilityDate"               =>  ["nullable", "string"],
        "energyEfficiencyClass"          =>  ["nullable", "string"],
        "expirationDate"                 =>  ["nullable", "string"],
        "expirationDate"                 =>  ["nullable", "string"],
        "installmentAmount"              =>  ["nullable", "string"],
        "installmentMonths"              =>  ["nullable", "string"],
        "loyaltyPoints"                  =>  ["nullable", "array"],
        "maxEnergyEfficiencyClass"       =>  ["nullable", "string"],
        "maxHandlingTime"                =>  ["nullable", "string"],
        "minEnergyEfficiencyClass"       =>  ["nullable", "string"],
        "minHandlingTime"                =>  ["nullable", "string"],
        "productHeight"                  =>  ["nullable", "array"],
        "productLength"                  =>  ["nullable", "array"],
        "productWeight"                  =>  ["nullable", "array"],
        "productWidth"                   =>  ["nullable", "array"],
        "return_policy_label"            =>  ["nullable", "string"],
        "salePriceEffectiveDate"         =>  ["nullable", "array"],
        "shipping"                       =>  ["nullable", "array"],
        "shippingHeight"                 =>  ["nullable", "array"],
        "shippingLabel"                  =>  ["nullable", "string"],
        "shippingLength"                 =>  ["nullable", "array"],
        "shippingWeight"                 =>  ["nullable", "array"],
        "shippingWidth"                  =>  ["nullable", "array"],
        "subscriptionCostAmount"         =>  ["nullable", "string"],
        "subscriptionCostPeriod"         =>  ["nullable", "string"],
        "subscriptionCostPeriodLength"   =>  ["nullable", "string"],
        "transitTimeLabel"               =>  ["nullable", "string"],
    ],
    'promotionTypeName' => [
        "MONEY_OFF" => "Amount off",
        "BUY_M_GET_MONEY_OFF" => "Buy quantity of products, get amount off",
        "BUY_M_GET_N_MONEY_OFF" => "Buy quantity of products, get the same item at a discount",
        "PERCENT_OFF" => "Percent off",
        "BUY_M_GET_PERCENT_OFF" => "Buy quantity of products, get percent off",
        "BUY_M_GET_N_PERCENT_OFF" => "Buy quantity of products, get the same item at a percent off",
        "FREE_GIFT" => "Get a free gift",
        "FREE_GIFT_WITH_VALUE" => "Get a gift card",
        "FREE_GIFT_WITH_ITEM_ID" => "Give a free gift from your inventory",
        "FREE_SHIPPING_STANDARD" => "Free standard shipping",
        "FREE_SHIPPING_OVERNIGHT" => "Free overnight shipping",
        "FREE_SHIPPING_TWO_DAY" => "Free 2-day shipping",
    ],
    'promotionForm' => [
        'promotionId' => 'required|string|min:1|max:50|alpha_dash',
        'longTitle' => 'required|string|min:1|max:60',
        'targetCountry' => ['required', 'exists:countries,code', 'string'],
        'contentLanguage' => ['required', 'string'],
        'couponValueType' => 'required|string',
        'promotionDestinationIds' => 'required|min:1|max:2',
        "offerType" => ["required", "string", "in:NO_CODE,GENERIC_CODE"],
        "genericRedemptionCode" => ["required_if:offerType,GENERIC_CODE", "string", "max:20"],
        "promotionDisplayTimePeriod" => ["required", "array", "min:2"],
        'promotionEffectiveTimePeriod.startTime' => ['regex:/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T(2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9].[0-9]{3}Z$/'],
        'promotionEffectiveTimePeriod.endTime' => ['regex:/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T(2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9].[0-9]{3}Z$/', 'after:now', 'after:promotionDisplayTimePeriod.startTime'],
        'promotionDisplayTimePeriod.startTime' => ['regex:/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T(2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9].[0-9]{3}Z$/', 'before:promotionEffectiveTimePeriod.endTime'],
        'promotionDisplayTimePeriod.endTime' => ['regex:/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T(2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9].[0-9]{3}Z$/', 'after:now', 'after:promotionDisplayTimePeriod.startTime'],
        'redemptionChannel.*' => 'required|min:1|in:ONLINE,IN_STORE',
        'minimumPurchaseAmount' => 'nullable',
        'minimumPurchaseAmount.value' => 'nullable|min:1|max:13',
        'moneyOffAmount' => 'required_if:couponValueType,MONEY_OFF,BUY_M_GET_MONEY_OFF,BUY_M_GET_N_MONEY_OFF|array',
        'minimumPurchaseQuantity' => 'required_if:couponValueType,BUY_M_GET_MONEY_OFF,BUY_M_GET_N_MONEY_OFF,BUY_M_GET_PERCENT_OFF,BUY_M_GET_N_PERCENT_OFF,BUY_M_GET_N_MONEY_OFF|min:1|max:3',
        'productApplicability' => 'required|string|in:ALL_PRODUCTS,SPECIFIC_PRODUCTS',
        'getThisQuantityDiscounted' => 'required_if:couponValueType,BUY_M_GET_N_MONEY_OFF,BUY_M_GET_N_PERCENT_OFF',
        'percentOff' => 'required_if:couponValueType,PERCENT_OFF,BUY_M_GET_PERCENT_OFF,BUY_M_GET_N_PERCENT_OFF|string',
        'freeGiftDescription' => 'required_if:couponValueType,FREE_GIFT|string|min:1|max:100',
        'freeGiftValue' => 'required_if:couponValueType,FREE_GIFT_WITH_VALUE|array|min:1|max:10|',
        'freeGiftItemId' => 'required_if:couponValueType,FREE_GIFT_WITH_ITEM_ID|string|max:50',
        // to be Continueeee.........................................
    ],
    'jsonEncodedColumns' => [
        'redemptionChannel',
        'promotionDestinationIds',
        'promotionEffectiveTimePeriod',
        'minimumPurchaseAmount',
        'moneyOffAmount',
        'freeGiftValue',
        'promotionDisplayTimePeriod'
    ],
    'columnsForDeletePromotion' => [
        'promotionId',
        'longTitle',
        'targetCountry',
        'contentLanguage',
        'couponValueType',
        'promotionDestinationIds',
        'offerType',
        'genericRedemptionCode',
        'promotionDisplayTimePeriod',
        'promotionEffectiveTimePeriod',
        'redemptionChannel',
        'minimumPurchaseAmount',
        'moneyOffAmount',
        'minimumPurchaseQuantity',
        'productApplicability',
        'getThisQuantityDiscounted',
        'percentOff',
        'freeGiftDescription',
        'freeGiftValue',
        'freeGiftItemId',
    ],
];
